[package]
name = "expectrl"
version = "0.1.3"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"
description = "A tool for automating terminal applications in Unix like Don libes expect"
repository = "https://github.com/zhiburt/expectrl"
homepage = "https://github.com/zhiburt/expectrl"
documentation = "https://docs.rs/expectrl"
license = "MIT"
categories = ["os::unix-apis"]
keywords = ["pty", "automation", "testing", "expect", "rexpect"]
readme = "README.md"

[features]
log = []

[target.'cfg(unix)'.features]
async = ["futures-lite", "async-io"]

[dependencies]
regex = "1.5.4"
futures-lite = { version = "1.12.0", optional = true }
async-io = { version="1.6.0", optional=true }

[target.'cfg(windows)'.dependencies]
conpty = { git = "https://github.com/zhiburt/conpty" }

[target.'cfg(unix)'.dependencies]
ptyprocess = { git = "https://github.com/zhiburt/ptyprocess" }
nix = "0.21.0"
