[package]
name = "expectrl"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.21.0"
async-fs = "1.5.0"
futures-lite = "1.12.0"
futures-timer = "3.0.2"
polling = "2.1.0"