[package]
name = "expectrl"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptyprocess = { git="https://github.com/zhiburt/ptyprocess", branch="main", ref="e007b827a571e328896f53176d9d38e47c168dc1" }
regex = "1.5.4"
