[package]
name = "expectrl"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptyprocess = { git="https://github.com/zhiburt/ptyprocess", branch="main", ref="998ccea688935b695fc15407ac49f3b9f7e24459" }
regex = "1.5.4"
