name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  mactest:
    name: AAAAA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- try_read_after_process_exit --show-output  --exact --nocapture
